server:
  port: 8889

logging:
  cofnig: classpath:log/logback.xml

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB
      file-size-threshold: 2KB
  jackson:
    serialization:
      write-dates-as-timestamps: true
file:
  head-sculpture: ./headSculpture